Step1  코드리뷰 요청드립니다
next-step/ddd-kitchenpos pull request #38
Opened 2019-11-21 12:02 UTC by daeheejeong

2019-11-24 00:33 UTC, wotjd243 requested changes
깔끔한 코드 구현이 좋았습니다. 👍 
간단한 생각거리를 남겼으니 코드에 반영해 주셔도 좋습니다.
진행 과정에서 궁금한 점은 댓글이나 Slack을 통해 물어보세요.

2019-11-24 00:33 UTC, wotjd243 commented on src/main/java/camp/nextstep/edu/calculator/Calculator.java
> +    private static final String DELIMITER_REGEX_CUSTOM = "//(.)\\n(.*)";
`String`을 패턴 매칭을 위해 `Pattern`으로 바꾸는 것은 꽤나 비싼 행위입니다. 미리 `Pattern`으로 만들어 사용하는 것은 어떨까요? 아래의 글을 참고하세요.
https://stackoverflow.com/questions/2469244/whats-the-difference-between-string-matches-and-matcher-matches/2469275

2019-11-24 00:33 UTC, wotjd243 commented on src/main/java/camp/nextstep/edu/calculator/Calculator.java
> +        String delimiter = "\\,|\\:";
매직 넘버는 의미를 나타낼 수 있는 상수로 치환하여 코드의 가독성을 높여 보는 것은 어떨까요?

2019-11-24 00:33 UTC, wotjd243 commented on src/main/java/camp/nextstep/edu/calculator/Calculator.java
> +        int parsedNumber = Integer.parseInt(number);
`Number` 클래스를 만들어 보면 어떨까요? 아래의 글이 도움 되면 좋겠어요.
https://www.slideshare.net/plusjune/ss-46109239

2019-11-24 00:33 UTC, wotjd243 commented on src/test/java/camp/nextstep/edu/calculator/CalculatorTest.java
> +    @Test
`@NullSource`와 `@EmptySource`를 사용하면 어떨까요? 아래의 글을 참고하세요.
https://www.baeldung.com/parameterized-tests-junit-5

```suggestion
    @ParameterizedTest
    @NullSource
    @EmptySource
```

2019-11-24 15:31 UTC, daeheejeong commented
조언해주신 내용들에 대해서 수정해보았습니다 !
Number 클래스를 사용하니 코드가 더 간결해 지고 이해가 용이해진 부분이 있는 것 같아요 :)
수정하면서 몇가지 궁금한 내용이 있었습니다.

- Number클래스를 사용하게 되면서 add(), sum() 함수에서 int <-> Number 간의 변환소요가 생기게 되었는데 이런부분이 혹시 성능 상에 있어서는 크게 문제가 없을지
- 매직넘버를 치환하는 과정에서 group() 함수에 전달한 인자들도 치환의 필요성이 있을지, 있다면 어떤식으로 네이밍을 가져가는 것이 읽기 좋은? 코드일지

이런 부분들에 대해서도 추가적으로 의견을 듣고싶습니다!

2019-11-25 13:02 UTC, wotjd243 requested changes
피드백을 전부 잘 반영해 주셨습니다. 💯 
질문에 대한 답변은 코멘트로 남겼어요.
다음 리뷰 요청 때는 Merge 하도록 하겠습니다.

2019-11-25 13:02 UTC, wotjd243 commented on src/main/java/camp/nextstep/edu/calculator/Calculator.java
> +        Number[] numbers = Arrays.stream(split(input))
배열 대신 컬렉션을 사용하면 어떨까요? 아래의 글이 도움 되면 좋겠어요.
https://madplay.github.io/post/prefer-lists-to-arrays

2019-11-25 13:02 UTC, wotjd243 commented on src/main/java/camp/nextstep/edu/calculator/Calculator.java
> +                .mapToInt(Number::getNumber)
`Number`에 메시지를 던지도록 구조를 바꿔 보면 어떨까요? 객체에 메시지를 보내 데이터를 가지는 객체가 일하도록 해보세요.

2019-11-25 15:25 UTC, daeheejeong commented
다시 조언해 주신 내용도 반영해보았습니다. 확인부탁드릴게요 :)
질문에 답변 주신 내용도 잘 확인했어요~ group 메서드의 경우에는 인자값의 의도가 명확하다고 판단해서 굳이 치환하지 않아도 될 것 같다고 판단했습니다!

2019-11-25 15:26 UTC, daeheejeong commented
다시 조언해 주신 내용도 반영해보았습니다. 확인부탁드릴게요 :)
질문에 답변 주신 내용도 잘 확인했어요~ group 메서드의 경우에는 인자값의 의도가 명확하다고 판단해서 굳이 치환하지 않아도 될 것 같다고 판단했습니다!

2019-11-26 07:17 UTC, wotjd243 approved these changes
피드백을 전부 잘 반영해 주셨습니다. 💯 
이만 Merge 하겠습니다.

2019-11-26 07:17 UTC, merged