Step1 : 문자열 덧셈 계산기 리뷰 요청드립니다.
next-step/ddd-kitchenpos pull request #44
Opened 2019-11-23 06:40 UTC by jaehun2841

2019-11-23 23:25 UTC, pangyocat requested changes
확실치는 않지만 Merge 된 이후에 upstream의 branch를 받아서 rebase하고 로컬 branch를 만들고 작성한 게 아니라 step0 commit을 fetch 받아서 로컬에서 merge한 후에 진행해서 그런게 아닐까 싶은데 확실치는 않네요. 😿 

약간의 피드백 남겼습니다. 확인해보시고 궁금한 점 있으면 메시지 남겨주세요.
남은 주말 잘 보내세요~ 😸

2019-11-23 23:25 UTC, pangyocat commented on src/main/java/camp/nextstep/edu/calculator/StringCalculator.java
> +    }
두 메소드가 달라보이지만 사실 굉장히 유사한 상태입니다. 조금 방향을 바꿔서 현재 token을 만드는 역할이 `add`, `hasCustomDelimeterExpression`, `extract`, `sum`에 조금씩 흩어져 있는데 한 곳으로 모으면 어떨까요?

2019-11-23 23:25 UTC, pangyocat commented on src/main/java/camp/nextstep/edu/calculator/StringCalculator.java
> +            throw new RuntimeException("숫자 이외의 값을 사용할 수 업습니다.");
요구 사항에 집중하다가 `RuntimeException`을 너무 의식한 케이스가 아닐까 싶습니다. 
`NumberFormatException`도  `RuntimeException`을 구현한 예외라 변환할 필요는 없습니다. 또한 표준 예외중 한 종류인 `NumberFormatException`을 `RuntimeException`으로 변환을 했기때문에 예외 발생시에 발생한 예외가 아닌 메시지에 의존해야 하는 상황이 되었습니다.

2019-11-23 23:25 UTC, pangyocat commented on src/main/java/camp/nextstep/edu/calculator/NegativeNumberException.java
> +public class NegativeNumberException extends Exception {
커스텀 exception 👍 

다만 꼭 필요한 경우가 아니라면 `RuntimeException`으로 만드셔도 될 것 같습니다!
복구 가능한 경우, API를 사용하는 측에서 발생한 문제를 처리하여 안정성을 높이는 경우를 빼고서는 보통은 `RuntimeException`을 사용하시면 됩니다.

사실 저도 checked exception을 만들어 사용해 본적은 없는데 안정성을 높이기 위한 이유로 결제, 정산 등 복구가 불가능한 경우라도 예외 처리를 안하면 큰 문제가 되는 API에 대해서는 사용측에 예외 처리를 강제하기 위해 사용하더군요.

참고할만한 자료로는 이펙티브 자바에 잘 나와있는데 정리된 링크를 찾진 못해서 아쉽지만 해당 아이템을 남깁니다. (3판 기준)
아이템 70. 복구할 수 있는 상황에는 검사 예외를, 프로그래밍 오류에는 런타임 예외를 사용하라
아이템 71. 필요 없는 검사 예외 사용은 피하라

2019-11-25 03:44 UTC, jaehun2841 commented on src/main/java/camp/nextstep/edu/calculator/StringCalculator.java
> +            throw new RuntimeException("숫자 이외의 값을 사용할 수 업습니다.");
앗 그렇네요!! 굳이 불필요한 짓을 하고 있었네요.
수정하도록 하겠습니다 :)

2019-11-25 03:45 UTC, jaehun2841 commented on src/main/java/camp/nextstep/edu/calculator/NegativeNumberException.java
> +public class NegativeNumberException extends Exception {
넵 코멘트 감사합니다 :)

2019-11-25 04:45 UTC, woowa-jaehun commented
@pangyocat 시간 내주셔서 코멘트 달아주셔서 감사합니다 :)

2019-11-25 15:09 UTC, pangyocat approved these changes
피드백 잘 반영해주세요 :)
merge하도록 하겠습니다~

2019-11-25 15:09 UTC, merged