1단계 - 문자열 덧셈 계산기
next-step/ddd-kitchenpos pull request #45
Opened 2019-11-23 09:14 UTC by kang-hyungu

2019-11-23 16:20 UTC, pangyocat requested changes
전체적으로 깔끔하게 잘 구현해주셨네요. 👍 

몇가지 피드백을 남겨두었으니 확인해보시고 궁금한 점 있으면 메시지 남겨주세요.
남은 주말 잘 보내세요~ 😸

2019-11-23 16:20 UTC, pangyocat commented on src/main/java/camp/nextstep/edu/calculator/StringCalculator.java
> +    }
filter로서 사용되고 있고 추가적인 stream 생성까지 하고 있는데 line 17에서 처리하면 어떨까요?

2019-11-23 16:20 UTC, pangyocat commented on src/main/java/camp/nextstep/edu/calculator/StringCalculator.java
> +        final Pattern pattern = Pattern.compile("//(.*)\\n(.*)");
Pattern 같은 경우는 생성하는 비용이 비싼 객체입니다. 현재 테스트 코드상에선 한번의 add만 있어서 문제가 없겠지만 add를 여러번 할 일이 있으면 매번 Pattern을 생성하게 됩니다.

이펙티브 자바에서도 `아이템 6: 불필요한 객체를 만들지 말자`에서 예로 설명되어 있는데 간단히 참고바랍니다.
https://github.com/keesun/study/blob/master/effective-java/item6.md

2019-11-23 16:20 UTC, pangyocat commented on src/main/java/camp/nextstep/edu/calculator/StringCalculator.java
> +    private Stream<String> splitByDelimiters(String text, String... delimiters) {
요구사항에 포함되진 않았는데 디폴트, 커스텀 구분자 둘 다 계산가능하게 하셨네요. 👍

2019-11-25 13:03 UTC, kang-hyungu commented on src/main/java/camp/nextstep/edu/calculator/StringCalculator.java
> +    }
음수 예외처리는 도메인 규칙으로 판단했습니다.
음수가 있는지 찾아 예외 발생하는 로직과 합을 구하는 로직을 분리하는게 읽기 좋은 코드라 생각해서 분리했으나 현재 규모에서는 굳이 분리할 필요가 없다고 생각되어 다시 합쳤습니다.

2019-11-25 14:53 UTC, pangyocat commented on src/main/java/camp/nextstep/edu/calculator/StringCalculator.java
> +    }
말씀처럼 빼기, 곱하기, 나누기가 들어온다면 기존 코드처럼 validation을 체크와 연산을 분리하는게 훨씬 좋은 코드라고 생각합니다 👍

2019-11-25 14:55 UTC, merged