[step1] 문자열 덧셈 계산기
next-step/ddd-kitchenpos pull request #47
Opened 2019-11-23 17:32 UTC by doooyeon

2019-11-24 08:38 UTC, pangyocat requested changes
깔끔한 구현에다 테스트 코드도 직접 작성해 주셨네요. 💯
간단한 피드백 남겨드렸는데 궁금한 점이 있으면 댓글이나 slack으로 문의 주세요 😄

2019-11-24 08:38 UTC, pangyocat commented on src/main/java/camp/nextstep/edu/calculator/CalculatorNumber.java
> +            throw new RuntimeException();
NumberFormatException은 표준 예외로 발생한 예외만 보고도 어떤 문제가 생긴건지 빠르게 대응 할 수 있지만 RuntimeException은(특히 아무 메시지도 없다면) 예외 발생시 stacktrace을 확인하며 문제의 원인을 찾아봐야 합니다. 
[이펙티브 자바 Item 72. 표준 예외를 사용하라](https://jaehun2841.github.io/2019/03/10/effective-java-item72/#%EC%84%9C%EB%A1%A0)
`Exception, RuntimeException, Throwable, Error는 직접 재사용하지 말자`는 이번 과제가 커스텀 예외를 활용하게 아니기 때문에 크게 고려하지 말아주세요!

또한 NumberFormatException이 이미 RuntimeException을 구현한 상태라 다시 RuntimeException을 던지게 할 필요는 없습니다.

2019-11-24 08:38 UTC, pangyocat commented on src/main/java/camp/nextstep/edu/calculator/CalculatorNumber.java
> +    static final CalculatorNumber ZERO = new CalculatorNumber(0);
default 접근 제한자를 의도하신거라면 👍

2019-11-24 08:38 UTC, pangyocat commented on src/main/java/camp/nextstep/edu/calculator/StringCalculator.java
> +        Matcher matcher = Pattern.compile(CUSTOM_DELIMITER_REGEX).matcher(text);
Pattern은 생성이 비싼 객체에 속합니다. add할 때마다 동일한 regex로 매번 생성하는데 미리 만들어두고 재활용하면 어떨까요? 
아래글 참고 해주세요.
https://stackoverflow.com/questions/2469244/whats-the-difference-between-string-matches-and-matcher-matches/2469275

2019-11-24 08:38 UTC, pangyocat commented on src/test/java/camp/nextstep/edu/calculator/CalculatorNumberTest.java
> +    @MethodSource("addCase")
👍

2019-11-25 13:34 UTC, doooyeon commented
꼼꼼한 리뷰 감사합니다. :)
리뷰 주신 부분 반영하여 다시 올렸습니다!

2019-11-25 14:42 UTC, pangyocat approved these changes
이전 설명이 부족했던 부분이 있어서 간단한 피드백 하나 남겨드렸습니다.
피드백 잘 반영해주셔서 merge하도록 할게요 😺

2019-11-25 14:42 UTC, pangyocat commented on src/main/java/camp/nextstep/edu/calculator/CalculatorNumber.java
> +            throw new IllegalArgumentException("Input must be numeric.", e);
원인이 되는 exception을 실어보내는 부분 👍 
제가 설명이 부족했었네요. 😿 
`NumberFormatException <- IllegalArgumentException <- RuntimeException` 이라서 사실 `IllegalArgumentException`로 바꿀 필요도 없답니다!

2019-11-25 14:42 UTC, merged