Step1
next-step/ddd-kitchenpos pull request #53
Opened 2019-11-24 15:06 UTC by teachd000000

2019-11-25 11:54 UTC, kyucumber commented on src/main/java/camp/nextstep/edu/calculator/StringNumberParser.java
> +    public static String[] parse(String text) {
상수 값이나 Util의 역할을 하는 게 아닌 경우 `static`으로 정의되지 않아도 될 것 같아요.
static으로 구현되어도 기능상 전혀 문제가 없지만, 꼭 필요한 부분경우에만 사용하는게 좋을것 같습니다!

2019-11-25 11:54 UTC, tramyu commented on src/main/java/camp/nextstep/edu/calculator/StringNumbers.java
> +                .reduce(0, Integer::sum);
아래와 같이 구현할수도 있을 것 같아요!
```java
items.stream()
  .mapToInt(StringNumber::getItem)
  .sum();
```

2019-11-25 11:54 UTC, tramyu commented on src/test/java/camp/nextstep/edu/calculator/NumberHelperTest.java
> +}
대부분의 파일에 newline이 빠져 있는데 아래 내용을 한번 참고해보셔도 좋을 것 같아요.
![image](https://user-images.githubusercontent.com/34656258/69198420-fb19b080-0b77-11ea-9581-7a6e72a3a9f4.png)

https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

> 인텔리제이에서 자동으로 저장 시 newline을 붙이도록 하는 설정

![image](https://user-images.githubusercontent.com/34656258/69198460-1be20600-0b78-11ea-83cd-c8fc5189c7ba.png)

2019-11-25 15:18 UTC, kyucumber requested changes
간단한 피드백 남겼습니다. 👍 
클래스나 메소드를 깔끔하게 나눠서 잘 구현하신 것 같아요!

2019-11-25 15:18 UTC, tramyu commented on src/main/java/camp/nextstep/edu/calculator/NumberHelper.java
> +public class NumberHelper {
`NumberHelper`의 경우 현재 isNegative 메소드를 `static`으로 정의하고 실제로
`StringNumber`의 validate()에서 밖에 사용되지 않는 것 같아요.
클래스의 분리와 역할의 분리도 좋지만, isNegative 메소드를 StringNumber에 private으로 선언하는게 조금 더 가독성 측면에서 좋을 것 같아요!

사람마다 스타일이 다르니 참고만 해주시면 좋을것 같습니다~

2019-11-25 15:18 UTC, tramyu commented on src/main/java/camp/nextstep/edu/calculator/StringNumber.java
> +            throw  new IllegalArgumentException();
throw 뒤 공백이 두칸 들어있어요!

그리고 IllegalArgumentException을 던지고 있는데 식별 가능한 예외 메세지를 추가해주시면 좋을 것 같아요.
```java
throw new IllegalArgumentException("Additional message");
```

2019-11-25 16:39 UTC, teachd000000 commented
피드백 반영했습니다.

2019-11-26 10:36 UTC, kyucumber approved these changes
고생하셨습니다 👍

2019-11-26 10:36 UTC, merged