Step1 - 문자열 덧셈 계산기
next-step/ddd-kitchenpos pull request #62
Opened 2019-11-26 01:18 UTC by Ryan-An

**문자열 덧셈 계산기** - 구분자 , 또는 : 경우
**커스텀 구분자 문자열 덧셈 계산기** - 실제로 구분자를 '//'와 '\n'의 사이에 커스텀 구분자를 지정

리뷰 요청드립니다. 감사합니다. 꾸벅!

2019-11-26 07:21 UTC, wotjd243 requested changes
깔끔한 코드 구현이 좋았습니다. 👍 
간단한 생각거리를 남겼으니 코드에 반영해 주셔도 좋습니다.
진행 과정에서 궁금한 점은 댓글이나 Slack을 통해 물어보세요.

2019-11-26 07:21 UTC, wotjd243 commented on src/main/java/camp/nextstep/edu/calculator/StringCalculator.java
> +	private static final String DELIMITER = ",|:";
들여쓰기에는 탭 문자가 사용되지 않습니다. 아래의 Google Java Style Guide를 참고해 주세요.

> Tab characters are not used for indentation.

```suggestion
    private static final String DELIMITER = ",|:";
```

2019-11-26 07:21 UTC, wotjd243 commented on src/main/java/camp/nextstep/edu/calculator/StringCalculator.java
> +	private static final String PATTERN_DELIMITER = "//(.)\n(.*)";
`String`을 패턴 매칭을 위해 `Pattern`으로 바꾸는 것은 꽤나 비싼 행위입니다. 미리 `Pattern`으로 만들어 사용하는 것은 어떨까요? 아래의 글을 참고하세요.
https://stackoverflow.com/questions/2469244/whats-the-difference-between-string-matches-and-matcher-matches/2469275

2019-11-26 07:21 UTC, wotjd243 commented on src/main/java/camp/nextstep/edu/calculator/StringCalculator.java
> +		int parsedNumber = Integer.parseInt(number);
`Number` 클래스를 만들어 보면 어떨까요? 아래의 글이 도움 되면 좋겠어요.
https://www.slideshare.net/plusjune/ss-46109239

2019-11-26 14:24 UTC, Ryan-An commented on src/main/java/camp/nextstep/edu/calculator/StringCalculator.java
> +		int parsedNumber = Integer.parseInt(number);
OOP에 따라서, util로 따로 분리 반영하였습니다!

2019-11-26 14:25 UTC, Ryan-An commented on src/main/java/camp/nextstep/edu/calculator/StringCalculator.java
> +	private static final String PATTERN_DELIMITER = "//(.)\n(.*)";
말씀해주신 링크 잘봤습니다. 감사합니다. 클래스변수로 반영했습니다.

2019-11-26 14:27 UTC, Ryan-An commented
> 깔끔한 코드 구현이 좋았습니다. 👍
> 간단한 생각거리를 남겼으니 코드에 반영해 주셔도 좋습니다.
> 진행 과정에서 궁금한 점은 댓글이나 Slack을 통해 물어보세요.

네 감사합니다. 변경된 부분이 있어서 머지가 불가능하네요. 머지 부탁드립니다.

2019-11-29 08:12 UTC, wotjd243 requested changes
피드백을 잘 반영해 주셨습니다. 👍 
간단한 생각거리를 남겼으니 코드에 반영해 주셔도 좋습니다.
다음 리뷰 요청 때는 Merge 하도록 하겠습니다.

2019-11-29 08:12 UTC, wotjd243 commented on src/main/java/camp/nextstep/edu/calculator/util/Number.java
> +public final class Number {
좋은 객체란 무엇일까요? 아래의 글은 읽고 느낀 점을 전체 코드에 반영해 보면 어떨까요?
https://codingnuri.com/seven-virtues-of-good-object

2019-12-14 10:39 UTC, wotjd243 approved these changes
피드백을 잘 반영해 주셨습니다. 👍 
이만 Merge 하겠습니다.

2019-12-14 10:40 UTC, merged